version: '3.4'

services:
  migrator:
    depends_on:
      - sqlserver
    image: ${DOCKER_REGISTRY-}migrator
    build:
      context: .
      dockerfile: Migrator/Dockerfile

  publisher:
    image: ${DOCKER_REGISTRY-}publisher
    build:
      context: .
      dockerfile: Publisher/Dockerfile
    depends_on:
      - migrator
      - rabbitmq
      - sqlserver
      - subscriber

  rabbitmq:
    environment:
      - RABBITMQ_ERLANG_COOKIE=RSPAZZFQBLQOZDAEOCCX
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=yourStrong(!)Password
      - RABBITMQ_DEFAULT_VHOST=/
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    hostname: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433

  statistics:
    image: ${DOCKER_REGISTRY-}statistics
    build:
      context: .
      dockerfile: Statistics/Dockerfile
    depends_on:
      - migrator
      - publisher
      - rabbitmq
      - sqlserver
      - subscriber
    ports:
      - 8081:80

  subscriber:
    image: ${DOCKER_REGISTRY-}subscriber
    build:
      context: .
      dockerfile: Subscriber/Dockerfile
    depends_on:
      - migrator
      - rabbitmq
      - sqlserver

  website:
    image: ${DOCKER_REGISTRY-}website
    build:
      context: .
      dockerfile: Website/Dockerfile
    depends_on:
      - migrator
      - publisher
      - rabbitmq
      - sqlserver
      - statistics
      - subscriber
    ports:
      - 8080:80
      